### ISSUE TITLE
KeyError: "Unable to open object (object 'data' doesn't exist)"

### ISSUE THREAD

**Issue by qixuxiang** [charlesq34/pointnet#122]
Thanks for your awesome code share!

I run the sem_seg code following  readme step by step, but when I run`python train.py --log_dir log6 --test_area 6`, there is an error:`KeyError: "Unable to open object (object 'data' doesn't exist)"`, here is details:

```
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    data_batch, label_batch = provider.loadDataFile(h5_filename)
  File "/usr/Downloads/pointnet/provider.py", line 97, in loadDataFile
    return load_h5(filename)
  File "/usr/Downloads/pointnet/provider.py", line 92, in load_h5
    data = f['data'][:]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/group.py", line 177, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'data' doesn't exist)"

```

I run the code in [tensorflow/tensorflow   1.7.1-devel-gpu](https://hub.docker.com/r/tensorflow/tensorflow/tags/) of `Python 2.7`, and I solve all the problem of dependency.

Looking forward to your response, thanks a lot!

**Comment by joanne1112** [comment]
Hi, 
Did you have trouble running `sh download_data.sh`?
I run it in the terminal it says:
`Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use --no-check-certificate.
unzip:  cannot find or open indoor3d_sem_seg_hdf5_data.zip, indoor3d_sem_seg_hdf5_data.zip.zip or indoor3d_sem_seg_hdf5_data.zip.ZIP.
rm: cannot remove 'indoor3d_sem_seg_hdf5_data.zip': No such file or directory`

I guess it might be the **ShapeNetSem** in the download category in the website. But not sure.
Could you please tell me how to solve this problem?
Thanks before!

Joanne

**Comment by hjsg1010** [comment]
II have the same problem. When the epoch train is in progress, the learning ends with the above message.
![image](https://user-images.githubusercontent.com/17421673/45401258-cc0dd200-b68a-11e8-8758-8e96cd473e7c.png)

**Comment by Lsesasfs** [comment]
Have you downloaded or prepared your hdf5 files properly? Usually there will be a folder named "indoor3d_sem_seg_hdf5_data" in folder sem_seg. And there should be two separate parts "data" and "label" in each .h5 file. I would recommend you to check the contents of your hdf5 files.

**Comment by dvirginz** [comment]
When you run python train.py for the first time it downloads the data for you
I have the same error, when running it locally (with sudo prevliges) it works, but on a remote server with a virtualenv I have the same error like qixuxiang

**Comment by zkm98** [comment]
I have the same question while using data from indoor3d_sem_seg_hdf5_data

**Comment by vajrag** [comment]
I faced this issue too. This can happen if the `xxx.h5` files are broken. 
Try to download the dataset again and train. This worked for me.
