### ISSUE TITLE
Certificate Has Expired Error

### ISSUE THREAD

**Issue by Beril-1** [charlesq34/pointnet#141]
Hello,
I try to use this work but unfortunately I have this error when I use "python train.py" command. 

--2018-10-04 09:56:37--  https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.
unzip:  cannot find or open modelnet40_ply_hdf5_2048.zip, modelnet40_ply_hdf5_2048.zip.zip or modelnet40_ply_hdf5_2048.zip.ZIP.
mv: cannot stat 'modelnet40_ply_hdf5_2048': No such file or directory
rm: cannot remove 'modelnet40_ply_hdf5_2048.zip': No such file or directory
Traceback (most recent call last):
  File "train.py", line 63, in <module>
    os.path.join(BASE_DIR, 'data/modelnet40_ply_hdf5_2048/train_files.txt'))
  File "/home/beril/catkin_ws/src/pointnet-master/provider.py", line 88, in getDataFiles
    return [line.rstrip() for line in open(list_filename)]
IOError: [Errno 2] No such file or directory: '/home/beril/catkin_ws/src/pointnet-master/data/modelnet40_ply_hdf5_2048/train_files.txt'

How can I solve this? Or is it just because of the licence expired? 

Thank you for any help.

**Comment by ThibaultGROUEIX** [comment]
@Beril-1 : It fails to download the data. Adding "--no-check-certificate" to the wget commant should solve the issue. My guess would be replace L15 of provider.py by 
```
    os.system('wget %s --no-check-certificate; unzip %s' % (www, zipfile))
```
best regards,
Thibault Groueix
