### ISSUE TITLE
Error when training sem_seg model with my own data

### ISSUE THREAD

**Issue by shinguncher** [charlesq34/pointnet#231]
I have created hdf5 files and when I ran train.py, it displayed this:

/home/junzheshen/pointnet/JS PointNet/PointNet 1000 ptsm2 without error/provider.py:91: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  f = h5py.File(h5_filename)
Traceback (most recent call last):
  File "train.py", line 70, in <module>
    data_batch, label_batch = provider.loadDataFile(h5_filename)
  File "/home/junzheshen/pointnet/JS PointNet/PointNet 1000 ptsm2 without error/provider.py", line 97, in loadDataFile
    return load_h5(filename)
  File "/home/junzheshen/pointnet/JS PointNet/PointNet 1000 ptsm2 without error/provider.py", line 91, in load_h5
    f = h5py.File(h5_filename)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
ValueError: Invalid file name (invalid file name)

**Comment by honggesmile** [comment]
hello,How to make my own dataset, can you give me some methods, thanks

**Comment by SERPENT-H** [comment]
How to convert las format to hdf5 format
请问楼主，怎么把las格式转换为hdf5格式，谢谢

**Comment by aiveforu** [comment]
> How to convert las format to hdf5 format
> 请问楼主，怎么把las格式转换为hdf5格式，谢谢

https://github.com/IsaacGuan/PointNet-Plane-Detection could help you
