### ISSUE TITLE
Running problems of part segmentation

### ISSUE THREAD

**Issue by chenMouRen1231** [charlesq34/pointnet#263]
When I run part segmentation, the program reports an error.
def get_transform(point_cloud, is_training, bn_decay=None, K = 3):
    """ Transform Net, input is BxNx3 gray image
        Return:
            Transformation matrix of size 3xK """
    batch_size = point_cloud.get_shape()[0].value
    num_point = point_cloud.get_shape()[1].value

Traceback (most recent call last):
  File "c:/Users/lenovo/Desktop/pointnet-master/part_seg/train.py", line 393, in <module>
    train()
  File "c:/Users/lenovo/Desktop/pointnet-master/part_seg/train.py", line 127, in train
    labels_pred, seg_pred, end_points = model.get_model(pointclouds_ph, input_label_ph, \
  File "c:\Users\lenovo\Desktop\pointnet-master\part_seg\pointnet_part_seg.py", line 82, in get_model
    transform = get_transform(point_cloud, is_training, bn_decay, K = 3)
  File "c:\Users\lenovo\Desktop\pointnet-master\part_seg\pointnet_part_seg.py", line 47, in get_transform
    batch_size = point_cloud.get_shape()[0].value
AttributeError: 'int' object has no attribute 'value'

**Comment by tosa-no-onchan** [comment]
You should be better to check its value.

print('>>> point_cloud.get_shape()=',point_cloud.get_shape())
>>> point_cloud.get_shape()= (16, 2048, 3)

Are there Integer value?
