### ISSUE TITLE
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:

### ISSUE THREAD

**Issue by monacv** [charlesq34/pointnet#264]
Hi thanks a lot for the interesting 3D computer vision research work.

Could you please have a look at the following error and guide me on how to fix it?
```

[35860:2264 0:981] 09:14:27 Mon Dec 28 [mona@goku:pts/5 +1] ~/research/code/DJ-RN/pointnet
$ python train.py 
--2020-12-28 21:14:32--  https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
ERROR: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Issued certificate has expired.
To connect to shapenet.cs.stanford.edu insecurely, use `--no-check-certificate'.
unzip:  cannot find or open modelnet40_ply_hdf5_2048.zip, modelnet40_ply_hdf5_2048.zip.zip or modelnet40_ply_hdf5_2048.zip.ZIP.
mv: cannot stat 'modelnet40_ply_hdf5_2048': No such file or directory
rm: cannot remove 'modelnet40_ply_hdf5_2048.zip': No such file or directory
Traceback (most recent call last):
  File "train.py", line 62, in <module>
    TRAIN_FILES = provider.getDataFiles( \
  File "/home/mona/research/code/DJ-RN/pointnet/provider.py", line 88, in getDataFiles
    return [line.rstrip() for line in open(list_filename)]
FileNotFoundError: [Errno 2] No such file or directory: '/home/mona/research/code/DJ-RN/pointnet/data/modelnet40_ply_hdf5_2048/train_files.txt'
6966/31772MB(base) 
```

**Comment by monacv** [comment]
Downloading manually with `--no-check-certificate ` flag works

```
[35860:2264 0:986] 09:19:11 Mon Dec 28 [mona@goku:pts/5 +1] ~/research/code/DJ-RN/pointnet
$ wget --no-check-certificate https://shapenet.cs.stanford.edu/ericyi/shapenetcore_partanno_v0.zip
--2020-12-28 21:19:21--  https://shapenet.cs.stanford.edu/ericyi/shapenetcore_partanno_v0.zip
Resolving shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)... 171.67.77.19
Connecting to shapenet.cs.stanford.edu (shapenet.cs.stanford.edu)|171.67.77.19|:443... connected.
WARNING: cannot verify shapenet.cs.stanford.edu's certificate, issued by ‘CN=InCommon RSA Server CA,OU=InCommon,O=Internet2,L=Ann Arbor,ST=MI,C=US’:
  Issued certificate has expired.
HTTP request sent, awaiting response... 200 OK
Length: 1078924697 (1.0G) [application/zip]
Saving to: ‘shapenetcore_partanno_v0.zip’
```


I followed the instructions in this commit: https://github.com/charlesq34/pointnet/pull/124/commits/96f4e36648e5878e62acc82ee1481e71e009c552
