### ISSUE TITLE
Add neuron to the ouput layer

### ISSUE THREAD

**Issue by Alfajesto** [charlesq34/pointnet#290]
Hi erveryone,
Is it possible to add a default neuron to the output layer? That if the analyzed structure does not correspond to any of the trained ones, I get an output like None

**Comment by Chengyuelan** [comment]
When I made the H5 data set, I encountered a problem. How could I solve it? I will be very grateful if I receive your reply.
@Alfajesto 
Traceback (most recent call last):
File "gen_indoor3d_h5.py", line 83, in
insert_batch(data, label, i == len(data_label_files))
File "gen_indoor3d_h5.py", line 58, in insert_batch
data_prep_util.save_h5(h5_filename, h5_batch_data, h5_batch_label, data_dtype, label_dtype)
File "/home/pointnetv2-master/utils/data_prep_util.py", line 80, in save_h5
h5_fout = h5py.File(h5_filename)
File "/home/anaconda3/envs/pointnetv2/lib/python3.7/site-packages/h5py/_hl/files.py", line 507, in init
fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
File "/home/anaconda3/envs/pointnetv2/lib/python3.7/site-packages/h5py/_hl/files.py", line 220, in make_fid
fid = h5f.open(name, flags, fapl=fapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
File "h5py/h5f.pyx", line 106, in h5py.h5f.open
FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = '/home/pointnet-master/data/indoor3d_sem_seg_hdf5_a_all_0.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
