### ISSUE TITLE
Unable to open H5py file 

### ISSUE THREAD

**Issue by VritangiKansal** [charlesq34/pointnet#292]
Any idea why I am getting the below error when I am trying to run the train.py file? 

**** EPOCH 000 ****
----0-----
/content/pointnet-master/provider.py:91: H5pyDeprecationWarning: The default file mode will change to 'r' (read-only) in h5py 3.0. To suppress this warning, pass the mode you need to h5py.File(), or set the global default h5.get_config().default_file_mode, or set the environment variable H5PY_DEFAULT_READONLY=1. Available modes are: 'r', 'r+', 'w', 'w-'/'x', 'a'. See the docs for details.
  f = h5py.File(h5_filename)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'data/modelnet40_ply_hdf5_2048/ply_data_train4.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)

**Comment by huamei0** [comment]
Hi @VritangiKansal , I'm also having the same problem when running gen_indoor3d_h5.py. Please let me know if you found the solution for this problem. Thank you

**Comment by ProgramWho** [comment]
@huamei0 Hello, I'm also having the same problem. How did you solved that?

**Comment by wangsale** [comment]
在 data_prep_util.py  把 h5_fout = h5py.File(h5_filename)  换成 h5_fout = h5py.File(h5_filename,'w')
