### ISSUE TITLE
OSError: raw write() returned invalid length 42 (should have been between 0 and 21)

### ISSUE THREAD

**Issue by yoshiyama** [charlesq34/pointnet#67]
Hello.

Pointnet was executed using python2.7, cuDNN5.1, CUDA8.0 under Windows 10 64bit.
The Error has been happened as follow.
Let me know how to solve it.

(tensorflow) C:\WORK\pointnet-master>python train.py
'cp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
'cp' は、内部コマンドまたは外部コマンド、
操作可能なプログラムまたはバッチ ファイルとして認識されていません。
Tensor("Placeholder_2:0", shape=(), dtype=bool, device=/device:GPU:0)
2017-12-22 23:33:14.875482: I C:\tf_jenkins\home\workspace\rel-win\M\windows\PY\35\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
**** EPOCH 000 ****
----0-----
mean loss: 3.888857
mean loss: 3.888857
Traceback (most recent call last):
  File "train.py", line 260, in <module>
    train()
  File "train.py", line 161, in train
    train_one_epoch(sess, ops, train_writer)
  File "train.py", line 212, in train_one_epoch
    log_string('mean loss: %f' % (loss_sum / float(num_batches)))
  File "train.py", line 70, in log_string
    print(out_str)
OSError: raw write() returned invalid length 42 (should have been between 0 and 21)

Yoshiyuki

**Comment by yoshiyama** [comment]
This issue has been solved using Anaconda Prompt(py27).
